export type VarKey =
  | "ADMIN_BOOTSTRAP_EMAIL"
  | "DEEPSEEK_API_BASE"
  | "IMAGE2_API_BASE"
  | "ALIYUN_OSS_BUCKET"
  | "ALIYUN_OSS_REGION"
  | "ALIYUN_OSS_OBJECT_PREFIX"
  | "WECHAT_PAY_ENABLED"
  | "WECHAT_PAY_NOTIFY_URL"
  | "WECHAT_PAY_API_BASE"
  | "WECHAT_PAY_ORDER_EXPIRE_MINUTES"
  | "WECHAT_PAY_CURRENCY";

export type SecretKey =
  | "USER_CREDENTIAL_MASTER_KEY"
  | "INVITE_CODE_HMAC_KEY"
  | "ALIYUN_OSS_ACCESS_KEY_ID"
  | "ALIYUN_OSS_ACCESS_KEY_SECRET"
  | "WECHAT_PAY_MCH_ID"
  | "WECHAT_PAY_APP_ID"
  | "WECHAT_PAY_MERCHANT_SERIAL_NO"
  | "WECHAT_PAY_API_V3_KEY"
  | "WECHAT_PAY_MERCHANT_PRIVATE_KEY_PEM"
  | "WECHAT_PAY_PUBLIC_KEY_ID"
  | "WECHAT_PAY_PUBLIC_KEY_PEM";
